pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
     - pip install -r requirements.txt -r requirements-tests.txt
     - flake8 --version
     - flake8
    when:
      branch: [ master ]
      event: [push, pull_request]
matrix:
  PYTHON_VERSION:
    - 2.7
